import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c] py-12 text-white">
        <div className="container mx-auto px-4">
          <h1 className="mb-10 text-center text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">T3</span> App Blog
          </h1>
          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <Link href={`#`} className="group">
                <div className="transform rounded-xl bg-white/10 p-6 transition-all duration-300 hover:bg-white/20">
                  <h3 className="mb-4 text-2xl font-bold group-hover:text-[hsl(280,100%,70%)]">
                    ブログのタイトル
                  </h3>
                  <div className="mb-4 text-lg">ブログの日付</div>
                  <span className="text-base text-gray-400">
                    2023/11/19
                  </span>
                </div>
              </Link>
              <Link href={`#`} className="group">
                <div className="transform rounded-xl bg-white/10 p-6 transition-all duration-300 hover:bg-white/20">
                  <h3 className="mb-4 text-2xl font-bold group-hover:text-[hsl(280,100%,70%)]">
                    ブログのタイトル
                  </h3>
                  <div className="mb-4 text-lg">ブログの日付</div>
                  <span className="text-base text-gray-400">
                    2023/11/19
                  </span>
                </div>
              </Link>
              <Link href={`#`} className="group">
                <div className="transform rounded-xl bg-white/10 p-6 transition-all duration-300 hover:bg-white/20">
                  <h3 className="mb-4 text-2xl font-bold group-hover:text-[hsl(280,100%,70%)]">
                    ブログのタイトル
                  </h3>
                  <div className="mb-4 text-lg">ブログの日付</div>
                  <span className="text-base text-gray-400">
                    2023/11/19
                  </span>
                </div>
              </Link>
          </div>
        </div>
      </main>
    </>
  );
}
